### ISSUE TITLE
test: add test to the theme functions

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#1265]
#### Add test
- [x] getBrightness
- [x] isDark
- [ ] attachThemeAttrs

### Define Specs
- [x] getBrightness - should return the right value
- [x] isDark - should return false with a light color
- [x] isDark - should return true with a dark color
- [ ] attachThemeAttrs - should return a merge object with props and  default themes values when props.theme.rainbow is an empty
- [ ] attachThemeAttrs - should return a merge object with props and props.theme.rainbow when props.theme.rainbow was passed

**Comment by yvmunayev** [comment]
@LeandroTorresSicilia check the specs

**Comment by LeandroTorresSicilia** [comment]
### Specs
## getBrightness:
- [ ] should return the right value
- [ ] should return the right value when color passed is hsl

## isDark
- [ ] should return false with a light color
- [ ] should return true with a dark color

## attachThemeAttrs
- [ ] should return a merged object with props and props.theme.rainbow
(Here we need only one test since getTheme needs to be mocked and only you need to test that the merge is made between props and what getTheme returns)
