### ISSUE TITLE
feat: implement the minus icon when some children are selected on the Tree component

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#1429]
### Requirements
- Implement a new example with a real use-case

### Specs
- Add the `indeterminate` state
- When the state of the checkmark is indeterminate a minus icon is rendered inside the checkbox

#### Review the example 4 on the design
https://zpl.io/blE8m9D

<img width="808" alt="Screen Shot 2020-04-03 at 11 26 28 AM" src="https://user-images.githubusercontent.com/32083556/78388368-196bd000-759e-11ea-8715-af5006bc3b07.png">

**Comment by LeandroTorresSicilia** [comment]
Steps:
1. Move table checkbox to src/components/PrimitiveCheckbox in order to reuse in both Table and Tree
2. Change prop checked in PrimitiveCheckbox to receive true | false | 'indeterminate'
3. Change Tree checked value in data shape to receive true | false | 'indeterminate'
4. When the checked value is undefined should not render the Checkbox in Tree component
