### ISSUE TITLE
fix: the page crash when `Tabset` component have only one Tab

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#1667]
<img width="404" alt="Screen Shot 2020-06-28 at 12 27 36 PM" src="https://user-images.githubusercontent.com/32083556/85954114-cdc98800-b93a-11ea-989f-6f7aeb3eac8c.png">

**Comment by gerardolgvr** [comment]
Hello! Can I try to fix this issue?

**Comment by TahimiLeonBravo** [comment]
> Hello! Can I try to fix this issue?

@gerardolgvr You are welcome :)
Go for it!

**Comment by gerardolgvr** [comment]
> > Hello! Can I try to fix this issue?
> 
> @gerardolgvr You are welcome :)
> Go for it!

Thanks, I think I found the solution to this issue. 

The problem was at the function "IsNotSameChildren" at utils.js. This function is expecting an array of objects but when a single tab is given the parameter that receives that function is an object. So, method .some is available for arrays but when an object is received an error occurs.

I have updated the function to check when an object is passed to the function to make the proper cooperation. 

The tests associated to this component runs without problems :) 

I think its a good moment to make a pr and check if it seems ok for you or if some changes are required 😊
