### ISSUE TITLE
fix: Chart legend never showing up

### ISSUE THREAD

**Issue by maximegheraille** [nexxtway/react-rainbow#2052]
-   [x] I have searched the [issues](https://github.com/nexxtway/react-rainbow/issues) of this repository and believe that this is not a duplicate.

## Describe the bug

There should be a legend on the chart but there is never one, even when adding specific options.

setting `legendPosition="bottom" showLegend={true}` does not show a legend and does not change to position of it because there is none

## To Reproduce 🕹

```
import React from 'react';
import { Chart, Dataset } from 'react-rainbow-components';

const containerStyles = {
    maxWidth: 600,
};

    <div className="rainbow-p-vertical_medium rainbow-m_auto" style={containerStyles}>
        <div className="rainbow-align-content_center">
            <Chart
                labels={['A', 'B', 'C', 'D']}
                type="line"
                className="rainbow-m-horizontal_xx-large rainbow-m-top_x-large"
              	legendPosition="bottom"
              	showLegend={true}
            >
                <Dataset
                    title="Dataset 1"
                    values={[23, 45, 123, 56]}
                    backgroundColor="#1de9b6"
                    borderColor="#1de9b6"
                />
                <Dataset
                    title="Dataset 2"
                    values={[66, 100, 30, 156]}
                    backgroundColor="#01b6f5"
                    borderColor="#01b6f5"
                />
            </Chart>
        </div>
    </div>
```

**Comment by HellWolf93** [comment]
@yvmunayev @reiniergs this is caused by [`unregisterGlobalPlugins`](https://github.com/nexxtway/react-rainbow/blob/09326ffb38f7cd46210efb6aaac580e1d6dbe112/src/components/Chart/index.js#L50) . I understand this is necessary to keep the chart plugins isolated, but this also removes default plugins like legend and title.

I think we should keep those plugins global since they provide basic functionality for the chart, would be awkward to pass those plugins to each chart.
