### ISSUE TITLE
fix: change body css when setting theme in DateTimePicker

### ISSUE THREAD

**Issue by chachacha912** [nexxtway/react-rainbow#2195]
-   [X] I have searched the [issues](https://github.com/nexxtway/react-rainbow/issues) of this repository and believe that this is not a duplicate.

## Describe the bug
Hi,  I use DateTimePicker in react-app.
I want to change theme color, so i add theme using <Application theme={theme}>.

  ~~~~
const theme = {
    rainbow: {
        palette: {
            brand: '#CA31A2',
        },
    },
};

<Application theme={theme}>
      <DateTimePicker
        formatStyle='large'
        onChange={(value) =>
            setStartDate(value)
        }
        minDate={new Date(minDate)}
        maxDate={new Date()}
        value={startDate}
    />
</Application>
  ~~~~

Expected Behavior 🤔 : only theme color change
Current Behavior 😯 : body font-size , <a> text-decoration are also changed(overwrite)
Can I just change color of theme in DateTimePicker?

##Screenshots
![image](https://user-images.githubusercontent.com/67041124/110427923-d0949380-80eb-11eb-9b37-14e7370376e0.png)
![image](https://user-images.githubusercontent.com/67041124/110428257-54e71680-80ec-11eb-8bce-461304731a48.png)

When I use <Application theme={theme}>, the problem is 
first, font-size of body changes smaller(0.8125rem), 
second, text-decoration of a tag changes to underline.

**Comment by HellWolf93** [comment]
Hi @chachacha912. I think this is happening because you are using the application component in the wrong way. As I understand, you are using the Application component to change the styles of one single component, while the application component is meant to be the base for the entire application.

You have two options:
1. Use the Application component as the base of your app, or
2. Use the [RainbowThemeContainer](https://react-rainbow.io/#/RainbowThemeContainer) component which is meant to provide the theme for specific parts of your tree.

If there is something I didn't understand correctly please reply on this issue.
