### ISSUE TITLE
fix:  remove javascript:void(0) from all components where it is used

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#876]

**Comment by OlivierJM** [comment]
is it possible to totally work on this issue, I have been using rainbow and I love it but react complains a lot on a couple of things but the major one is the `javascript:void`
https://github.com/nexxtway/react-rainbow/blob/c9cac8f0180b85b1c53065b75245c649f59e3b06/src/components/MenuItem/index.js#L90

I would love to help on this if this is open for contribution.

**Comment by LeandroTorresSicilia** [comment]
@OliverJM Of course, it is open for contribution, but this issue needs to be carefully discussed since it is not trivial.
The best option that I saw is convert these anchors to buttons but here there is a problem because the menu item can be used for navigation and for other actions, in the navigation case it should be an anchor and for other actions it should be a button.
Also there is the case when you navigate using onClick instead of href so ideally we need to use anchor with onClick but the anchor needs the href to keep the right behavior.
If you have any thoughts about how this can be resolved tell us.

**Comment by OlivierJM** [comment]
Hi @LeandroTorresSicilia Thanks for the clarification, I had not thought of the double usage of the component and that makes it a little more complex.
One way I would think about which react doesn't complain about is leaving the href blank 

`<a href role="menuitem" aria-disabled={disabled} ref={this.itemRef}></a>`

and if the navigation issue is on styling maybe we can style a button to look like an anchor tag though we would still lose some things like :visited

**Comment by LeandroTorresSicilia** [comment]
after some discussion here are some ideas to follow:
1. Components that use anchor only with onClick we need to change to use button instead.
2. Components that use anchor with href and onClick should render an anchor when href is passed otherwise a button.
